### ISSUE TITLE
Artifactory is not being updated with latest helm chart versions

### ISSUE THREAD

**Issue by sanjaypjana** [netbox-community/netbox-chart#211]
I am trying to starting using the latest versions of netbox. As of Yesterday i see there is a new version of chart available (netbox-5.0.0-beta12) but looks like the artifactory does not have a version of it. By any chance can we have latest chart version pushed to artifactory hub.

**Comment by RangerRick** [comment]
This is a thing I intend to do once we are out of beta, since there are some pretty big changes going on under the covers.

In the meantime, you can play with the new charts by using https://charts.netbox.oss.netboxlabs.com/

(I'll leave this open for now as a reminder that I need to update the README to point to the new repo.)
